### ISSUE TITLE
O que o warsaw-openrc oferece?

### ISSUE THREAD

**Issue by ninrod** [ryukinix/warsaw-openrc#1]
Fala @ryukinix. Acredito que seja tranquilo falar em português, já que esse cancer maligno parece afetar apenas os bancos do Brasil, que eu saiba.

É tranquilo usar o warsaw no arch com esse seu pacote? 

Tem como desinstalar ou ele domina a sua máquina, a sua vida e a sua alma? 

Se uso o systemd eu preciso do seu pacote? vi que vc tem umas opções pra systemd. 

O que exatamente o seu pacote resolve em termos no contexto do vírus warsaw? 

Obrigado desde já

**Comment by ryukinix** [comment]
Se você usa systemd você não precisa dele, embora meu pacote tenha suporte pra quem usa systemd também. A questão é que uso uma derivação do Arch Linux sem SystemD: Artix Linux. Por questões pessoais mesmo que esse issue é muito limitado pra entrarmos numa longa discussão do porque da minha decisão.

Tem como desinstalar ele depois de instalado sim. Não domina não. É o que uso pessoalmente na minha máquina e cuido com cautela os rastros dele. Atualmente essa versão está precisando de mudanças porque infelizmente ocorreu inúmeros problemas mais cancerígenos que só no AUR pra você ler a merda que ta dando e você precisa  hackear o file system com `chattr` pra ter um comportamento não auto-destrutivo do pacote.

O warsaw, se você realmente sabe o que é, é um componente necessário para o funcionamento pleno de alguns bancos, incluindo o Banco do Brasil mas existe muitos outros usando também (para o nosso azar). Infelizmente eles nos obriga hoje assim como obriga há muito tempo usuários do Windows.

Esse pacote é destinado ao desejo de usar o Warsaw para ter internet banking funcionando juntamente com o serviço configurável não-intrusivo pelo OpenRC (init system).

Espero que isso esclaresca  a suas maiorias dúvidas. Maiores referências você pode ler essa thread: [warsaw]

Caso você ainda tiver interesse de instalar esse pacote mesmo usando systemd, comente aqui, mas acredito que você terá mais sucesso sem as modificações com a versão upstream do [warsaw]

[warsaw]: https://aur.archlinux.org/packages/warsaw/

**Comment by ninrod** [comment]
entendi. 

bom. como alternativa, dá pra usar o warsaw dentro de um container se vc usa bb code. 

sobe o container, usa o banco, mata o container. tem um camarada meu que usa assim no mac. 

dá uma olhada [aqui](https://github.com/lichti/containers4docker/issues/8#issuecomment-330369627)

abs,

**Comment by ryukinix** [comment]
Eu geralmente só subo o serviço manualmente e depois dou stop.

`service start warsaw`

> access internet banking

`service stop warsaw`

Mas até que é bom a ideia de deixar num container, pena que não gosto tanto da ideia de ter o dockerd rodando sempre no meu sistema, dai vai se resumir a um problema parecido com o meu de caso de uso, embora tenha a proteção de virtualização do filesystem e isolamento.

**Comment by ninrod** [comment]
problema é que sempre que atualiza o warsaw vc não sabe o que pode acontecer. no contexto do container a merda fica isolada dentro de um container efêmero.

**Comment by ryukinix** [comment]
De fato é um backdoor que roda como root e pode fazer o que bem 
entender. Faz sentido o uso do container. Obrigado por compartilhar, 
aposto que vai ser útil pra alguém que acaber vendo essa thread.

Abraço.
-- 
As lembranças não são só do passado. Podem ser de agora e até de 
amanhã.
— Serial Experiments Lain
Manoel Vilela,
Discente em Engenharia da Computação,
Universidade Federal do Ceará.
